language: emacs-lisp
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install emacs-25.1-travis --use --skip
  - YES=1 make
script:
  - make test
